### ISSUE TITLE
iframe2image___default(...) is not a function error in Angular 4

### ISSUE THREAD

**Issue by sumit140** [twolfson/iframe2image#5]
Hi ,

I am using Angular 4 and inside the iframe i have called my 3rd party visualization url to export the iframe content what i have did is 

- I have installed npm install iframe2image
-After that import iframe2image from 'iframe2image';
- on click i have called 
$("#btnSave-parent").click(function() { 
          var canvas: any = document.getElementById('canvas');
          var context = canvas.getContext('2d');
          canvas.width = 500;
          canvas.height = 600;
      // Grab the iframe
      var inner = document.getElementById('pcp');
      // Get the image
      iframe2image(inner, function (err, img) {
        // If there is an error, log it
        if (err) { return console.error(err); }
        // Otherwise, add the image to the canvas
        context.drawImage(img, 0, 0);
      });
      });
Also import the script files:
"scripts": [
             "../node_modules/iframe2image/dist/iframe2image.min.js",
             "../node_modules/iframe2image/lib/domvas.js"
        ],
After that i am getting below mentioned error could you please suggest me how i can resolve that issue.
![image](https://user-images.githubusercontent.com/6861473/51891631-b729a500-23c5-11e9-8425-d65a5209fd77.png)

**Comment by twolfson** [comment]
This seems like a configuration issue or an import with Webpack which is outside of the scope of this project. I'd recommend reducing/simplifying the code until you find an example which reproduces the error. If it does turn out to be the project, please let us know and we'll gladly help fix it
