### ISSUE TITLE
Canvas didn't work when there is image in iframe ?

### ISSUE THREAD

**Issue by abbiewu** [twolfson/iframe2image#6]
Hello,

If I have the image(ex: background-image:url(test.png);) in my iframe, and I use iframe2image to convert my iframe into canvas.
However, the canvas won't show the backgroung-image.

Here is my sample code.
https://repl.it/@taihsinwu/Test-iframe-to-canvas

Does anybody have the same issue?

Thanks!

**Comment by twolfson** [comment]
There's a few possible options I can think of:

- Cross-domain issue prevents image in iframe from being referenced
- Asynchronous loading of background image causes it to not load immediately in SVG
- SVG might not support background images
- Something else

The implementation this library uses is quite simple so it can miss complex cases. I'm deciding to archive the project as this library is often impractical and not an ideal solution for what people actually need (e.g. screenshotting tool via PhantomJS or Electron)
